world_collision_model:
  frame_id: world
  size_x: 2.0
  size_y: 3.0
  size_z: 2.0
  origin_x: -1.0
  origin_y: -2.0
  origin_z: 0.0
  res_m: 0.02
  max_distance_m: 0.6

self_collision_model:
  frame_id: world
  size_x: 3.0
  size_y: 3.0
  size_z: 2.0
  origin_x: -1.5
  origin_y: -2.0
  origin_z: 0.0
  res_m: 0.02
  max_distance_m: 0.2

robot_collision_model:
  world_joint:
    name: world # This the joint to which the base is attached.
    type: fixed # fixed, floating

  spheres_models:
    - link_name: cruzr_base_link
      auto: false
      spheres:
        - { name: t0, x: 0.0, y: 0.0, z: -0.03, radius: 0.19, priority: 1  }
        - { name: t1, x: 0.0, y: 0.0, z: -0.10, radius: 0.19, priority: 1  }
        - { name: b0, x: 0.0, y: 0.0, z: -0.359, radius: 0.285, priority: 4 }

    - link_name: base_link
      auto: false
      spheres:
        #- { name: n0, x: 0.0, y: 0.0, z: -0.12, radius: 0.20, priority: 1 }
        - { name: n0, x: 0.0, y: 0.0, z: -0.12, radius: 0.10, priority: 1 }
    - link_name: head_l1
      auto: false
      spheres:
          - { name: h0, x: 0., y: 0.0, z: 0.0, radius: 0.00, priority: 4 }
    - link_name: head_l2
      auto: false
      spheres:
          - { name: h0, x: 0.0, y: 0.120, z: 0.0, radius: 0.15, priority: 4 }
    - link_name: right_limb_l1
      auto: false
      spheres:
          #- { name: r10, x: 0.0, y: 0.0, z: 0, radius: 0.08, priority: 1 }
          - { name: r10, x: 0.0, y: 0.0, z: -0.03, radius: 0.07, priority: 1 }
    - link_name: right_limb_l2
      auto: false
      spheres:
        - { name: r20, x: 0.0, y: 0.115, z: 0.0, radius: 0.05, priority: 5 }
    - link_name: right_limb_l3
      auto: false
      spheres:
        - { name: r30, x: 0.03, y: 0.0, z: 0.0, radius: 0.05, priority: 4 }
    - link_name: right_limb_l4
      auto: false
      spheres:
        - { name: r40, x: 0.03, y: 0.08, z: 0.0, radius: 0.04, priority: 4 }
    - link_name: right_limb_l5
      auto: false
      spheres:
        - { name: rlo0, x: 0, y: 0.0, z: -0.05, radius: 0.04, priority: 2 }
        - { name: rlo0, x: 0, y: 0.0, z: -0.03, radius: 0.04, priority: 2 }
        - { name: rlo0, x: 0, y: 0.0, z: 0.00, radius: 0.04, priority: 2 }
    - link_name: right_limb_l6
      auto: false
      spheres:
        - { name: rlo0, x: 0, y: 0.0, z: 0.00, radius: 0.04, priority: 2 }
    - link_name: right_limb_l7
      auto: false
      spheres:
        - { name: rlo0, x: 0, y: 0.0, z: 0.0, radius: 0.00, priority: 2 }
    - link_name: right_palm_link
      auto: false
      spheres:
          - { name: rp0, x: -0.01, y: -0.02, z: 0.02, radius: 0.055, priority: 2 }
          - { name: rp1, x: -0.01, y: -0.1, z: 0.01, radius: 0.055, priority: 2 }
          - { name: rp2, x: 0.05, y: -0.03, z: 0.03, radius: 0.03, priority: 2 }
    - link_name: left_limb_l1
      auto: false
      spheres:
          #- { name: r10, x: 0.0, y: 0.0, z: 0, radius: 0.08, priority: 1 }
          - { name: r10, x: 0.0, y: 0.0, z: -0.03, radius: 0.07, priority: 1 }
    - link_name: left_limb_l2
      auto: false
      spheres:
        - { name: r20, x: 0.0, y: -0.115, z: 0.0, radius: 0.05, priority: 5 }
    - link_name: left_limb_l3
      auto: false
      spheres:
        - { name: r30, x: 0.03, y: 0.0, z: 0.0, radius: 0.05, priority: 4 }
    - link_name: left_limb_l4
      auto: false
      spheres:
        - { name: r40, x: 0.03, y: -0.08, z: 0.0, radius: 0.04, priority: 4 }
    - link_name: left_limb_l5
      auto: false
      spheres:
        - { name: rlo0, x: 0, y: 0.0, z: -0.05, radius: 0.04, priority: 2 }
        - { name: rlo0, x: 0, y: 0.0, z: -0.03, radius: 0.04, priority: 2 }
        - { name: rlo0, x: 0, y: 0.0, z: 0.00, radius: 0.04, priority: 2 }
    - link_name: left_limb_l6
      auto: false
      spheres:
        - { name: rlo0, x: 0, y: 0.0, z: 0.00, radius: 0.04, priority: 2 }
    - link_name: left_limb_l7
      auto: false
      spheres:
        - { name: rlo0, x: 0, y: 0.0, z: 0.0, radius: 0.00, priority: 2 }
    - link_name: left_palm_link
      auto: false
      spheres:
          - { name: rp0, x: 0.0, y: -0.02, z: 0.02, radius: 0.05, priority: 2 }
          - { name: rp1, x: -0.01, y: -0.1, z: 0.01, radius: 0.05, priority: 2 }
          - { name: rp2, x: -0.05, y: -0.03, z: 0.03, radius: 0.03, priority: 2 }


  collision_groups:
    - name: right_arm
      links:
          - name: right_limb_l1
          - name: right_limb_l2
          - name: right_limb_l3
          - name: right_limb_l4
          - name: right_limb_l5
          - name: right_palm_link
    - name: left_arm
      links:
          - name: left_limb_l1
          - name: left_limb_l2
          - name: left_limb_l3
          - name: left_limb_l4
          - name: left_limb_l5
          - name: left_palm_link
    - name: base
      links:
          - name: base_link
          - name: cruzr_base_link
          - name: head_l1
          - name: head_l2
    - name: right_arm_base
      groups: [right_arm, base]
    - name: full_body
      groups: [right_arm, left_arm, base]
    - name: head
      links:
        - name: head_l1
        - name: head_l2
    - name: right_gripper
      links:
        - name: right_palm_link
